name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - v5

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - name: Inject Legal HTML Disclaimer
        run: |
          find content -name "*.md" -type f -exec sh -c 'echo "" >> "{}"; echo "<div class=\"legal-disclaimer\" style=\"margin-top: 20px; padding-top: 10px; border-top: 1px dashed gray; font-family: sans-serif; text-align: center;\"><p style=\"font-size: 12px !important; color: gray !important; line-height: 1.4 !important;\"><b> Возрастная категория: 18+</b> (Запрещено для детей в соответствии с Федеральным законом № 436-ФЗ). <br>Все материалы данного ресурса являются некоммерческим литературным творчеством и художественным вымыслом автора.</p><p style=\"font-size: 16px; color: dark-gray;\">© Hiddenheið | Dirk.Intj | 2026. Все права защищены.</p></div>" >> "{}"' \;
      - run: npx quartz build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
